"""21 9:30

Revision ID: 730138e47210
Revises: 
Create Date: 2024-10-21 09:37:10.806658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '730138e47210'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professionals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doc', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professionals', schema=None) as batch_op:
        batch_op.drop_column('doc')

    # ### end Alembic commands ###
